
# data parameters
dataset_name: mnist
train_data_path: dataset/capsule/train/
checkpoint_path: checkpoints/capsule/hole_benchmark
n_channel: 3
image_size: 28  # {MNIST, Fashion-MNIST}:28, CIFAR10: 32, {COIL100, MVTec, Medical}:128
normal_class: 0


# training parameters
num_epochs: 2000
batch_size: 128   # 8 for MVTec and medical datasets

# Unet
base_channel: 64
lr_u: 0.001
weight_decay: 1e-5

# Discriminator
n_extra_layers: 0
lr_d: 0.0002
beta1: 0.5
beta2: 0.999

# Learning_rate Scheduler
factor: 0.8   # 0.5 for MNIST
patience: 50  # 30 for MNIST


# FGSM Attack
eps: 0.1    # MNIST:0.1, {Fashion-MNIST, Medical}:0.07, {CIFAR10, COIL100}:10/255, MVTec:0.01
alpha: 2

# Adversarial Loss
adv_coeff: 0.02


