# data parameters
dataset_name: mnist
#test_data_path: dataset/capsule/train/
#checkpoint_path: checkpoints/capsule/hole_benchmark
n_channel: 1
image_size: 28  # {mnist, fashionmnist}:28, cifar10: 32, {coil100, MVTec, Medical}:128
normal_class: 8
last_epoch: 0

batch_size: 8   # 8 for MVTec and medical datasets

# Unet
base_channel: 64



