
# data parameters
dataset_name: mnist
test_data_path: dataset/capsule/train/
checkpoint_path: checkpoints/capsule/hole_benchmark
channel: 3
image_size: 28  # {MNIST, Fashion-MNIST}:28, CIFAR10: 32, {COIL100, MVTec, Medical}:128
normal_class: 0

batch_size: 128   # 8 for MVTec and medical datasets

# Unet
base_channel: 64



